In [7]:
import os
import pandas as pd
import regex as re
pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings("ignore")

In [8]:
path_o = str(os.getcwd()).split("\\")
path_o = "\\".join(path_o[:-1])

In [9]:
os.chdir(path_o+"\\data\\raw")
df_raw = pd.read_csv("data_clean_2_EDA.csv", index_col=0)
df_raw.head()

,budget,genres,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,crew,cast,keywords,title,year,month,day,market_share_genres,genres_all,production_companies_all,production_countries_all,spoken_languages_all,keywords_all,cast_all,people_vaccinated,people_fully_vaccinated,total_boosters,New_cases,New_deaths
0,7.405126e+07,Action,11.773,Ross Hunter Productions,United States of America,1970-05-29,7.441348e+08,137.0,Italian,George Seaton,Burt Lancaster,bomb,Airport,1970,5,29,0.141761,"['Action', 'Drama', 'Thriller']",['Ross Hunter Productions'],['United States of America'],"['Italian', 'English']","['bomb', 'based on novel or book', 'airport', ...","['Burt Lancaster', 'Dean Martin', 'Jean Seberg...",0.0,0.0,0.0,0.0,0.0
1,2.962050e+07,Adventure,13.786,Katzka-Loeb,United States of America,1970-01-01,3.850665e+07,144.0,English,Brian G. Hutton,Clint Eastwood,gold,Kelly's Heroes,1970,1,1,0.080776,"['Adventure', 'Comedy', 'War']","['Katzka-Loeb', 'Avala Film', 'Metro-Goldwyn-M...",['United States of America'],"['English', 'French', 'German']","['gold', 'world war ii', 'armor', 'campaign', ...","['Clint Eastwood', 'Telly Savalas', 'Don Rickl...",0.0,0.0,0.0,0.0,0.0
2,2.221538e+07,Adventure,25.768,APJAC Productions,United States of America,1970-04-23,1.406953e+08,95.0,English,Ted Post,James Franciscus,mutant,Beneath the Planet of the Apes,1970,4,23,0.080776,"['Adventure', 'Science Fiction', 'Mystery']","['APJAC Productions', '20th Century Fox']",['United States of America'],['English'],"['mutant', 'dystopia', 'astronaut', 'ape', 'wo...","['James Franciscus', 'Kim Hunter', 'Maurice Ev...",0.0,0.0,0.0,0.0,0.0
3,7.405126e+07,Adventure,7.547,Sir Nigel Films,United Kingdom,1970-10-29,1.110769e+07,125.0,German,Billy Wilder,Robert Stephens,loch ness monster,The Private Life of Sherlock Holmes,1970,10,29,0.080776,"['Adventure', 'Comedy', 'Crime', 'Mystery', 'R...","['Sir Nigel Films', 'United Artists', 'The Mir...",['United Kingdom'],"['German', 'French', 'Russian', 'English']","['loch ness monster', 'german spy', 'midgets']","['Robert Stephens', 'Colin Blakely', 'Genevi√®v...",0.0,0.0,0.0,0.0,0.0
4,1.110769e+08,Adventure,8.597,Cinema Center Films,United States of America,1970-12-14,2.337024e+08,139.0,English,Arthur Penn,Dustin Hoffman,based on novel or book,Little Big Man,1970,12,14,0.080776,"['Adventure', 'Western', 'Comedy', 'Drama']","['Cinema Center Films', 'Stockbridge-Hiller Pr...",['United States of America'],['English'],"['based on novel or book', 'indian territory',...","['Dustin Hoffman', 'Faye Dunaway', 'Chief Dan ...",0.0,0.0,0.0,0.0,0.0

In [10]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5340 entries, 0 to 5339
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   budget                    5340 non-null   float64
 1   genres                    5340 non-null   object
 2   popularity                5340 non-null   float64
 3   production_companies      5340 non-null   object
 4   production_countries      5340 non-null   object
 5   release_date              5340 non-null   object
 6   revenue                   5340 non-null   float64
 7   runtime                   5340 non-null   float64
 8   spoken_languages          5340 non-null   object
 9   crew                      5340 non-null   object
 10  cast                      5340 non-null   object
 11  keywords                  5340 non-null   object
 12  title                     5340 non-null   object
 13  year                      5340 non-null   int64
 14  month                     5340 non-null   int64
 15  day                       5340 non-null   int64
 16  market_share_genres       5340 non-null   float64
 17  genres_all                5340 non-null   object
 18  production_companies_all  5340 non-null   object
 19  production_countries_all  5340 non-null   object
 20  spoken_languages_all      5340 non-null   object
 21  keywords_all              5340 non-null   object
 22  cast_all                  5340 non-null   object
 23  people_vaccinated         5340 non-null   float64
 24  people_fully_vaccinated   5340 non-null   float64
 25  total_boosters            5340 non-null   float64
 26  New_cases                 5340 non-null   float64
 27  New_deaths                5340 non-null   float64
dtypes: float64(10), int64(3), object(15)
memory usage: 1.2+ MB

In [11]:
df_raw.columns

Index(['budget', 'genres', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'crew', 'cast', 'keywords', 'title', 'year',
       'month', 'day', 'market_share_genres', 'genres_all',
       'production_companies_all', 'production_countries_all',
       'spoken_languages_all', 'keywords_all', 'cast_all', 'people_vaccinated',
       'people_fully_vaccinated', 'total_boosters', 'New_cases', 'New_deaths'],
      dtype='object')

In [12]:
os.chdir(path_o+"\\utils")
from process_data import process_data_ML
df = process_data_ML(df_raw)
df.head()

,budget,genres,popularity,production_companies,production_countries,revenue,runtime,spoken_languages,crew,cast,keywords,month,day,market_share_genres,people_vaccinated,people_fully_vaccinated,total_boosters,New_cases,New_deaths
0,7.405126e+07,0,11.773,1724,70,7.441348e+08,137.0,36,790,313,147,5,29,0.141761,0.0,0.0,0.0,0.0,0.0
1,2.962050e+07,1,13.786,1071,70,3.850665e+07,144.0,19,280,434,504,1,1,0.080776,0.0,0.0,0.0,0.0,0.0
2,2.221538e+07,1,25.768,45,70,1.406953e+08,95.0,19,2304,887,796,4,23,0.080776,0.0,0.0,0.0,0.0,0.0
3,7.405126e+07,1,7.547,1837,69,1.110769e+07,125.0,27,247,1843,681,10,29,0.080776,0.0,0.0,0.0,0.0,0.0
4,1.110769e+08,1,8.597,406,70,2.337024e+08,139.0,19,174,591,104,12,14,0.080776,0.0,0.0,0.0,0.0,0.0

In [31]:
os.chdir(path_o+"\\data\\processed")
df.to_csv("data_processed.csv")